### ISSUE TITLE
Equivalent to FileViewPro

### ISSUE THREAD

**Issue by songlinshu** [mmalecot/file-format#20]
HI,Is there a content preview program that supports these files?

**Comment by mmalecot** [comment]
Hi, I don't quite understand your question. Do you have an example? What exactly do you want to do?

**Comment by songlinshu** [comment]
https://www.fileviewpro.com/en

**Comment by mmalecot** [comment]
No, there is no program similar to FileViewPro: you can happily write one using this crate. Beware, such a program will be dependent on the platform in which it is run. Some file formats supported by this crate have no program to open them.
