### ISSUE TITLE
More kind types

### ISSUE THREAD

**Issue by autriz** [mmalecot/file-format#21]
Hello, is there any possibility for new kind types, such as archives, documents, executables, etc.?

**Comment by mmalecot** [comment]
Hello, 

That's in my goals! Today the kinds are defined according to the media types.
I need to categorize the whole 300 formats.
Feel free to open a PR if you want.

**Comment by mmalecot** [comment]
Hello,

As requested, I've added several extra kinds.
These types may differ from those defined by IANA (media type/MIME).

Everything is being pushed to the dev branch, and will soon be released in version 0.17.

Feel free to give me your feedback!
