### ISSUE TITLE
Detect SVG when XML declaration is missing

### ISSUE THREAD

**Issue by petru-tazz** [mmalecot/file-format#22]
Hello,

I'm currently working on a project that relies heavily on `file-format` to handle images by it's media type accordingly.

I've just finished implementation for SVG support in our app and, while testing, the crate failed to detect correctly that [our logo](https://web.archive.org/web/20230315120048im_/https://webstatic.tazz.ro/build/media/tazz-logo.b20a07d6.svg) is a SVG. The main reason is that it lacks the `<?xml` declaration, so the code [never reaches this part](https://github.com/mmalecot/file-format/blob/main/src/readers.rs#L189).

After looking in our (source) SVGs, I found that there are many cases:
- some of them contains `<?xml` declaration;
- some of them contains `xmlns` attribute on `<svg>`;

The key point of this issue that, [as per this doc](https://oreillymedia.github.io/Using_SVG/extras/ch01-XML.html), `<?xml` is optional unless the encoding is not UTF-8 or UTF-16.

While I made a patch for our needs (and willing to finish up the PR), I wanted to open this issue to talk about other SVG versions and how it can be treated better for wider / more general use.

**Comment by mmalecot** [comment]
Hello,

Thanks for your PR!

Indeed, some XML-based formats such as SVG may not be detected. After some research, it turns out that XML 1.0 has an optional declaration whereas with XML 1.1 it is mandatory.

Ideally, I will have to deal with all XML-base formats when they do not have an XML declaration. I will comment directly on your PR for SVG.

**Comment by mmalecot** [comment]
Hi,

The patch will be available in version 0.17 later this week.

**Comment by mmalecot** [comment]
Hi,

I'm a bit late because I also wanted to resolve #21 for version 0.17.
I'm going to do a bit of code review, the release should arrive very soon!

**Comment by mmalecot** [comment]
Version 0.17.0 published including this fix!
Thanks!
