### ISSUE TITLE
Support for multi-format files / check against singular format

### ISSUE THREAD

**Issue by konata-chan404** [mmalecot/file-format#29]
Hi 👋
I love this project, such amazing selection of file formats~ I'm not sure if I didn't manage to comprehend the macro sorcery fully but is there a way to check if file contains multiple types (such as various [esoteric file polygots](https://github.com/netspooky/BGGP/tree/main/2021) )?

If not, just checking for every singular file individually would be great. thank you so much for the help <3

**Comment by mmalecot** [comment]
Hi,

Thanks for the compliment, I hope you'll manage to understand how these macros work, I'll add more comments in the code in the next version to make everything as clear as possible :).

I didn't know about polyglot files, that's very interesting, thanks for sharing!

Currently, `file-format` via `FileFormat::from_file` will return only one file format: the first one for polyglot files.

On the other hand, with `FileFormat::from_reader` or `FileFormat::from_bytes`, it should be possible to identify all the formats contained in a polyglot file, if we can determine the beginning of each of them.

Thanks for asking!

**Comment by mmalecot** [comment]
If you think it's possible and useful, we can also imagine a `polyglot` feature that activates a `FileFormat::from_polyglot_file` method, but I don't think it's easy to delimit sub-files.

**Comment by mmalecot** [comment]
Yes, please keep me posted!
Feel free to open a PR, I'll follow your project!
