### ISSUE TITLE
Possibility of ignoring certain control chars in txt reader

### ISSUE THREAD

**Issue by SomeRandoNamedDave** [mmalecot/file-format#30]
Hi, I'll open by saying thanks for writing this lib, I've been testing a few different crates of this type for a file previewer I'm writing and this is the best I've found.

This is more of a request rather than an actual issue, I mostly write terminal centric code and a lot of it features a handful of control chars (mostly terminal escape char and bell char), this causes the src files to be detected as the default "application/octect-stream" instead of "text/plain" and so my app skips generating a preview for these files.

Would you be open to adding some control char exclusions to from_txt_reader()?

I'm currently using a local fork that changes the function to
``` rust
    pub(crate) fn from_txt_reader<R: Read + Seek>(reader: &mut BufReader<R>) -> Result<Self> {
        // Constants for limits.
        const READ_LIMIT: u64 = 8_388_608;
        const LINE_LIMIT: usize = 256;

        // Rewinds to the beginning of the stream.
        reader.rewind()?;

        // Determines if the reader contains mostly ASCII/UTF-8-encoded text by checking the first
        // lines for control characters other than whitespace and certain select control characters.
        reader
            .take(READ_LIMIT)
            .lines()
            .take(LINE_LIMIT)
            .try_for_each(|line| {
                line?
                    .chars()
                    .find(|char| if char.is_control() {
                        match *char {
                            '' => false,
                            '' => false,
                            _ if char.is_whitespace() => false,
                            _ => true
                        }
                    } else { false })
                    .map(|_| Err(Error::new(ErrorKind::InvalidData, "Invalid characters")))
                    .unwrap_or(Ok(()))
            })
            .map(|_| Self::PlainText)
    }
```

I used a match statement to make it easier to add more options later if needed.

I can open a PR with the changes if this is something you're ok with, thanks for your time / consideration.

**Comment by SomeRandoNamedDave** [comment]
You're right about this solution being more of a hack, changing my code would be the better option in this instance.

Using the ascii chars was a habit I picked up from writing portable shell scripts, some older / more limited shells (ash, used by busybox or dash for example) don't interpret \e \x1b etc.

this isn't an issue with rust and most other languages plus the shell scripts are identified by the shebang anyway

Thanks for the response!

**Comment by mmalecot** [comment]
For the moment I prefer to keep the current heuristic because it seems to be more relevant and reliable.

To be seen later.

Thanks for your time!
