### ISSUE TITLE
[new requirement] would you support metadata for audio/video files? both read and write

### ISSUE THREAD

**Issue by lazebird** [mmalecot/file-format#35]
As a hobby project, I want to batch edit my movie tags, but I don't want to have to identify the file formats and metadata in my repository, and would love to have a third party repository that can do the job
I would like to ask if this project will consider extending the metadata for identifying video and audio files and provide setting capabilities?

**Comment by mmalecot** [comment]
Thanks for your question!

This is not planned for the moment because it's not really the objective of this crate. However, it's perfectly possible to combine it with other tools to carry out your project.
