### ISSUE TITLE
MKV shows as Application

### ISSUE THREAD

**Issue by Zerowalker** [mmalecot/file-format#39]
As title says, i got 2 mkvs, one is version 2 the other version 4,
both are shown as "application" instead of "video".

Name on both shows as: `Extensible Binary Meta Language`

**Comment by mmalecot** [comment]
Which version of `file-format` are you using?
Did you enable the `reader-ebml` feature?

**Comment by mmalecot** [comment]
Any news about this issue?

Please find [on docs.rs](https://docs.rs/file-format/0.21.0/file_format/#crate-features) the crate features details.

If it's still KO after enabling the `reader-ebml` feature using the last version of the crate, please provide me a sample of MKV file.

**Comment by Zerowalker** [comment]
Oh i didn't know about `reader-ebml`.

I am using 0.21.0, and enabling the above features made it work as expected.

Sorry!
