### ISSUE TITLE
Handle handle complex "svg headers"  starting with <?xml version="1.0" encoding="utf-8"?>

### ISSUE THREAD

**Issue by rustchain64** [mmalecot/file-format#41]
FileFormat does not parse complex or mixed "svg" files.
To handle this, there is a need for code to parse through the xml header to find an instance of the <svg.... within a range.

Example case:

Parsing....as_bytes()
```
<?xml version="1.0" encoding="utf-8"?>
<!-- Generator: Adobe Illustrator 27.4.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 viewBox="0 0 375.5 134.2" style="enable-background:new 0 0 375.5 134.2;" xml:space="preserve">
```
Using FileFormat::from_bytes(&buffer);
```
let format = FileFormat::from_bytes(&buffer);
 if format == FileFormat::ScalableVectorGraphics {
    debug!( Is format a SVG file: {}",
        format.media_type()
    );
} esle ....
```

It should be that the the parser drills past the <?xml ... to see if <?svg exists within a text/xml format, since it is always possible this text/xml is in fact an svg format.

FileFormat can only parse the <?xml node in this example.

**Comment by mmalecot** [comment]
Normally this should work with the `reader-xml` feature (see https://docs.rs/file-format/0.22.0/file_format/#reader-features).

Please check you have enabled the feature in your `Cargo.toml`.

**Comment by rustchain64** [comment]
Malecot
Thanks for your timely response
I will enable
feature=reader-xml
And test later today
Again thanks and regards
Wesley @ Diba.io

**Comment by rustchain64** [comment]
Closing Issue
