### ISSUE TITLE
Add Toney files

### ISSUE THREAD

**Issue by Pierre-Gronau-ndaal** [mmalecot/file-format#44]
Please be so kind and support

- https://crates.io/crates/rinex

as well

**Comment by mmalecot** [comment]
Thanks for this issue!

I'm not at all familiar with RINEX so I'll look into it and see if there's anything I can do.

If you have any references/specifications related to RINEX file formats I'm also interested.

**Comment by Pierre-Gronau-ndaal** [comment]
- https://files.igs.org/pub/data/format/rinex305.pdf

**Comment by mmalecot** [comment]
RINEX is an exchange format based on plain text or a gzip file. It's a bit complicated to detect simply, so for the moment no support.

Thanks!
