### ISSUE TITLE
Does not detect file shebangs with extra whitespace

### ISSUE THREAD

**Issue by blmaier** [mmalecot/file-format#56]
File-format's shebang based checks (e.g. `#!/usr/bin/env bash`) do not match against shebangs with extra whitespace. For example the following is a valid shebang `#!  /usr/bin/env     bash` but will not match as file-format looks only for static strings.

[Any number of spaces or tabs may be present after the #! and between each argument](https://en.wikipedia.org/wiki/Shebang_(Unix)#Syntax)

One solution could be to do what the libmagic library does, use a [whitespace flag that treats any whitespace in a pattern as 0 or more whitespaces](https://github.com/file/file/blob/8accfb88ab7411b4f62326ee230a917cae21e64c/magic/Magdir/commands#L73).

**Comment by mmalecot** [comment]
Hello and thank you for the issue.

I already knew about this problem, but given the way `file-format` is constructed, it implies that this type of format should no longer be handled by signature, but rather with text parsing.

I'll think about what I can do for the next release.

**Comment by mmalecot** [comment]
For the time being, parsing text requires a bit of work within `file-format`, as the crate isn't really built for it. It's something I've always had in the back of my mind, but for the moment I'm going to keep it simple. 

I'll see if I get around to it in the future, as I'll have to change the way almost all text-based file formats are handled to improve it.

Thanks again for the suggestion and don't hesitate to make others!
