### ISSUE TITLE
Support Glyphs source file `.glyphs`

### ISSUE THREAD

**Issue by yisibl** [mmalecot/file-format#58]
This is the source file for the font design software [Glyphs](https://glyphsapp.com/).

**Comment by mmalecot** [comment]
Thanks for this issue!
Do you know where I can find a free .glyphs sample?

**Comment by yisibl** [comment]
See https://github.com/googlefonts/zcool-xiaowei/blob/main/sources/xiaowei.glyphs

In addition, Glyphs generates the `.glyphspackage` file, see: https://github.com/atelier-anchor/smiley-sans/tree/main/src/SmileySans.glyphspackage

**Comment by mmalecot** [comment]
Implemented in 0.25.0.
Thanks for the suggestion!
