### ISSUE TITLE
`FLAC` file with ID3 tags incorrectly recognized as `MP3`

### ISSUE THREAD

**Issue by G2-Games** [mmalecot/file-format#65]
I have a `FLAC` music file which contains ID3 tags, and it is being recognized as an `MP3` file. I can provide the file if you need.

**Comment by mmalecot** [comment]
I'll take a look, please send me the file :).

**Comment by G2-Games** [comment]
Here is one file that exhibits the behavior. Unfortunately, it seems like it would be hard to correct for it as it has the exact same header as a regular MP3 with tags, except after the tags you end up with the proper FLAC signature.

[example.zip](https://github.com/user-attachments/files/17546973/example.zip)

**Comment by mmalecot** [comment]
I'm gonna check, thanks!

**Comment by G2-Games** [comment]
No it's not, check out a bit later in the stream at 0x122F. Also try running `ffprobe` on it. It's a FLAC with ID3 tags, which shouldn't exist.

**Comment by mmalecot** [comment]
I fixed this problem on dev branch.
It will be available in version 0.26.

Please note that the `reader-id3v2` feature is required for this to work properly.

@G2-Games You can try it on and give me feedback :).

**Comment by G2-Games** [comment]
Your fix seems to work great! Thank you very much.

**Comment by mmalecot** [comment]
Crate version 0.26.0 has just been published.
